### ISSUE TITLE
Add support for chat colors

### ISSUE THREAD

**Issue by Dids** [cgarnier/rust-admin#5]
Since chat messages support a few HTML tags, adding support for colors would be a nice addition.
Alternatively you could remove HTML tags from the output, so it's easier to read.
I know plenty of modded servers use a lot of colors/tags too, so this should be a common scenario.

Here's an example message:
```
<color=#FFE4C4>poliisi</color> <color=#DC143C>said goodbye to</color> <color=#FFE4C4>Peruna</color>
```

**Comment by cgarnier** [comment]
I will add that.
Do you know if there is other tags then color ?

**Comment by Dids** [comment]
Not sure, but I think I've seen tags like <b> and <i> used. As far as I know, they're using this: https://docs.unity3d.com/Manual/StyledText.html

There could be some cases where the colors could be too dark to be displayed, so one option would be to have a tick box for enabling/disabling colors/tags.

**Comment by cgarnier** [comment]
v1.3.0 will have the feature. 
I didnt implemented the size stuff. I think it will break the chat.

**Comment by Dids** [comment]
I agree, thanks! :)
